### ISSUE TITLE
In-Display fingerprint unlock feature lighting up after screen unlock (unicorn)

### ISSUE THREAD

**Issue by zzzz0317** [cupid-development/android_device_xiaomi_sm8450-common#3]
After installing the update on March 14th, my unicorn device encountered some issues with the in-display fingerprint unlock feature. The symptom is as follows: after unlocking the screen, touching the fingerprint unlock area causes it to light up. Could this be related to this commit?

https://github.com/cupid-development/android_device_xiaomi_sm8450-common/commit/b32b6cc1f54aae8b793a44ee62f53555de8624e5

![屏幕截图 2024-03-17 111500](https://github.com/cupid-development/android_device_xiaomi_sm8450-common/assets/16097046/e6b33ebf-5130-4636-8b31-5854500d286d)

**Comment by zzzz0317** [comment]
https://github.com/cupid-development/android_device_xiaomi_sm8450-common/assets/16097046/0ad7d4ed-5eec-4a39-a08d-b654209cdaf1

**Comment by ArianK16a** [comment]
Hey, can you reproduce the issue on the build from the 18th?

**Comment by ArianK16a** [comment]
Nevermind, i was able to reproduce it. Fixed by https://github.com/cupid-development/android_kernel_xiaomi_sm8450/commit/9c45635a52a0f888e8c5233e7fcc4b07fb3d19b2
