### ISSUE TITLE
Suggestion for codename replacement for zeus

### ISSUE THREAD

**Issue by truly-irham** [cupid-development/android_device_xiaomi_sm8450-common#5]
Hi,

First of all, I hope I'm not too late for suggesting this, but here you go :) I would like to suggest an alternative codename for Zeus as follows:

- **Zeus** -> **Eros** (instead of Zeus -> Dagda)

I personally think "Eros" would be a more suitable codename replacement than "Dagda" for the following reasons:

1. Eros is the Greek equivalent of the Roman Cupid [1]. Since Zeus is Greek, replacing Zeus with Eros makes more sense thematically as both codenames are Greek gods, unlike Dagda who is a chief god in Irish Celtic mythology [2].
2. Cupid and Eros are equivalent to each other as per my first point above, and hence better depicting the relationship between Xiaomi 12 and Xiaomi 12 Pro.
3. Zeus and Eros share common syllables and only four letters, creating a more consistent naming scheme compared to Dagda.
4. Finally, as a Zeus user myself, I'm not a big fan of the name "Dagda" because it sounds worse compared to Zeus. I think Eros would sound much better and be easier to work with.

I have already searched (as far as I could) for the codename "Eros" and haven't found any devices with a similar codename, even in the CyanogenMod device list.

I hope you can consider my suggestion. Whatever the final decision is, I will definitely support it.

Cheers!

[1] https://www.brandeis.edu/now/2022/february/joel-christensen-cupid.html
[2] https://www.britannica.com/topic/Dagda

**Comment by RITEFANG** [comment]
Good name for it.I think it's beter.
But here I always understand "dagda" as old and big phones in the 1970s .
So if we consider the meaning of cupid and the relationship between the two phones I think eros could be much more suitable.

**Comment by truly-irham** [comment]
Hey, since the device tree repo with the name "Dagda" has already been reserved in the official LineageOS github repo [here](https://github.com/LineageOS/android_device_xiaomi_dagda), I guess this suggestion is no longer relevant. I will be closing this issue when zeus gets its first official LineageOS release. Cheers!

**Comment by ArianK16a** [comment]
Thanks for the suggestion, we went for dagda since that's the closest representation of zeus in a different mythology which we found. Eros would have been a nice name too, but the repositories on the lineage organization are already created and we won't be able to rename them again.

**Comment by truly-irham** [comment]
You're most welcome! Good luck with bringing all hawaii devices to official LineageOS. 

Cheers!

**Comment by RITEFANG** [comment]
Thanks for your efforts! Wish all the best in the future!

Minus
