### ISSUE TITLE
I found a bug in build AOSP 15!

### ISSUE THREAD

**Issue by HeroRickyGAMES** [cupid-development/android_device_xiaomi_sm8450-common#8]
Hello everything is fine? I found a bug in the build! I found a problem that only happens when you build on Android 15!
I'm trying to build CRDROID with Android 15.
This happens with several other systems based on Android 15.

Log:
FAILED: out/target/product/marble/obj/SHARED_LIBRARIES/libwfdnative_intermediates/check_elf_files.timestamp
/bin/bash -c "(rm -f out/target/product/marble/obj/SHARED_LIBRARIES/libwfdnative_intermediates/check_elf_files.timestamp ) && (out/host/linux-x86/bin/check_elf_file --skip-bad-elf-magic --skip-unknown-elf-machine --soname libwfdnative.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libandroid_runtime_intermediates/libandroid_runtime.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libui_intermediates/libui.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libinput_intermediates/libinput.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libnativehelper_intermediates/libnativehelper.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libutils_intermediates/libutils.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/liblog_intermediates/liblog.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libwfdclient_intermediates/libwfdclient.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libhidlbase_intermediates/libhidlbase.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libhidlmemory_intermediates/libhidlmemory.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libbinder_intermediates/libbinder.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libgui_intermediates/libgui.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/[android.hidl.base@1.0_intermediates](mailto:android.hidl.base@1.0_intermediates)/[android.hidl.base@1.0.so](mailto:android.hidl.base@1.0.so) --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/[android.hidl.token@1.0-utils_intermediates](mailto:android.hidl.token@1.0-utils_intermediates)/[android.hidl.token@1.0-utils.so](mailto:android.hidl.token@1.0-utils.so) --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/[android.hardware.graphics.common@1.0_intermediates](mailto:android.hardware.graphics.common@1.0_intermediates)/[android.hardware.graphics.common@1.0.so](mailto:android.hardware.graphics.common@1.0.so) --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/[android.hardware.graphics.bufferqueue@1.0_intermediates](mailto:android.hardware.graphics.bufferqueue@1.0_intermediates)/[android.hardware.graphics.bufferqueue@1.0.so](mailto:android.hardware.graphics.bufferqueue@1.0.so) --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/[android.hardware.graphics.bufferqueue@2.0_intermediates](mailto:android.hardware.graphics.bufferqueue@2.0_intermediates)/[android.hardware.graphics.bufferqueue@2.0.so](mailto:android.hardware.graphics.bufferqueue@2.0.so) --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libc_intermediates/libc.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libm_intermediates/libm.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libc++_intermediates/libc++.so --shared-lib out/target/product/marble/obj/SHARED_LIBRARIES/libdl_intermediates/libdl.so --system-shared-lib libc --system-shared-lib libm --system-shared-lib libdl --llvm-readobj=prebuilts/clang/host/linux-x86/clang-r522817/bin/llvm-readobj out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so ) && (touch out/target/product/marble/obj/SHARED_LIBRARIES/libwfdnative_intermediates/check_elf_files.timestamp )"
out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so: error: Unresolved symbol: _ZN7android11MotionEvent10initializeEiijiNSt3__15arrayIhLm32EEEiiiiiiNS_20MotionClassificationERKNS_2ui9TransformEffffS8_llmPKNS_17PointerPropertiesEPKNS_13PointerCoordsE
out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so: error: Unresolved symbol: _ZN7android8KeyEvent10initializeEiijiNSt3__15arrayIhLm32EEEiiiiiill
out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so: note:
out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so: note: Some dependencies might be changed, thus the symbol(s) above cannot be resolved.
out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so: note: Please re-build the prebuilt file: "out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so".
out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so: note:
out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so: note: If this is a new prebuilt file and it is designed to have unresolved symbols, add one of the following properties:
out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so: note: Android.bp: allow_undefined_symbols: true,
out/soong/.intermediates/vendor/xiaomi/sm8450-common/libwfdnative/android_arm64_armv9-a_cortex-a510_shared/27c748455cfc32d4740a544b4e254ae6/libwfdnative.so: note: Android.mk: LOCAL_ALLOW_UNDEFINED_SYMBOLS := true

**Comment by ArianK16a** [comment]
These trees are meant to be used for LineageOS, this commit addressed your issue a month ago... https://github.com/LineageOS/android_hardware_lineage_compat/commit/140cc4986ba03de7c99242adc6a04e58b956d211

**Comment by HeroRickyGAMES** [comment]
Can you or have I managed to make a build of Android 15 for Marble?

**Comment by HeroRickyGAMES** [comment]
I've been facing this problem for a while now... If I comment on this libry the device doesn't boot
